[package]
name = "plantuml-stdlib"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Стандартная библиотека PlantUML (иконки, спрайты)"
keywords = ["plantuml", "stdlib", "icons"]

[dependencies]
